# Generated by Django 5.1.6 on 2025-02-18 16:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Jmeno: ")),
                ("surname", models.CharField(max_length=32, verbose_name="Prijmeni: ")),
                (
                    "street_number",
                    models.CharField(max_length=50, verbose_name="Ulice/c.p.: "),
                ),
                ("city", models.CharField(max_length=32, verbose_name="Mesto: ")),
                ("postal_code", models.IntegerField(verbose_name="PSC: ")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="Telefon: "
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email: ",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Datum narozeni: ")),
                (
                    "is_valid",
                    models.BooleanField(
                        default=False, verbose_name="Ucet v poradku?: "
                    ),
                ),
            ],
            options={
                "ordering": ["surname"],
            },
        ),
        migrations.CreateModel(
            name="UserPicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        upload_to="media.employee_img", verbose_name="img 1: "
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        upload_to="media.employee_img", verbose_name="img 2:"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        upload_to="media.employee_img", verbose_name="img 3:"
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="app_main.employee",
                        verbose_name="Zamestnanec: ",
                    ),
                ),
            ],
        ),
    ]
