# Generated by Django 5.1.6 on 2025-03-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facevector",
            name="face_vector_fernet",
            field=models.TextField(blank=True, verbose_name="vector fernet:"),
        ),
    ]
