# Generated by Django 5.1.6 on 2025-03-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facevector",
            name="face_vector",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Face vector:"
            ),
        ),
    ]
