# Generated by Django 5.1.6 on 2025-03-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0002_alter_facevector_face_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facevector",
            name="face_vector_fernet",
            field=models.BinaryField(
                blank=True,
                db_index=True,
                null=True,
                unique=True,
                verbose_name="vector fernet:",
            ),
        ),
    ]
