# Generated by Django 5.1.6 on 2025-03-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0002_facevector_face_vector_fernet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facevector",
            name="face_vector_fernet",
            field=models.BinaryField(blank=True, verbose_name="vector fernet:"),
        ),
    ]
