# Generated by Django 5.1.6 on 2025-02-18 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0003_alter_employee_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(
                max_length=16,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(5)],
                verbose_name="Telefon: ",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="postal_code",
            field=models.CharField(
                max_length=5,
                validators=[django.core.validators.MinLengthValidator(5)],
                verbose_name="PSC: ",
            ),
        ),
    ]
