# Generated by Django 5.1.6 on 2025-03-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0003_alter_facevector_face_vector_fernet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facevector",
            name="face_vector_fernet",
            field=models.BinaryField(
                blank=True, null=True, verbose_name="vector fernet:"
            ),
        ),
    ]
