# Generated by Django 5.1.6 on 2025-03-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0004_alter_facevector_face_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facevector",
            name="face_vector",
            field=models.JSONField(blank=True, verbose_name="Face vector:"),
        ),
    ]
