# Generated by Django 5.1.6 on 2025-02-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0005_alter_userpicture_image1_alter_userpicture_image2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_valid",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Ucet v poradku?: "
            ),
        ),
    ]
