# Generated by Django 5.1.6 on 2025-03-15 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0005_alter_facevector_face_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="city",
            field=models.CharField(max_length=32, verbose_name="Město:"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(verbose_name="Datum narození:"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Jméno:"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="postal_code",
            field=models.CharField(
                max_length=5,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.RegexValidator(
                        message="PSČ musí obsahovat 5 číslic.", regex="^\\d{5}$"
                    ),
                ],
                verbose_name="PSČ:",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="street_number",
            field=models.CharField(max_length=50, verbose_name="Ulice/č.p.:"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="surname",
            field=models.CharField(max_length=32, verbose_name="Příjmení:"),
        ),
    ]
