# Generated by Django 5.1.6 on 2025-03-15 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0006_alter_employee_city_alter_employee_date_of_birth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("working", "V práci"),
                            ("sick_leave", "Nemocenská"),
                            ("business_trip", "Služební cesta"),
                            ("vacation", "Dovolená"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Stav",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_main.employeestatus",
                verbose_name="pracovni status",
            ),
        ),
    ]
