# Generated by Django 5.1.6 on 2025-02-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0006_employee_slug_alter_employee_is_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
