# Generated by Django 5.1.6 on 2025-03-16 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0008_alter_employeestatus_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeestatus",
            options={},
        ),
    ]
