# Generated by Django 5.1.6 on 2025-02-19 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0008_alter_employee_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                max_length=100, unique=True, verbose_name="Email: "
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(
                max_length=16,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.RegexValidator(
                        message="Telefon musí být ve správném formátu.",
                        regex="^\\+?[0-9\\s\\-()]{5,16}$",
                    ),
                ],
                verbose_name="Telefon: ",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="postal_code",
            field=models.CharField(
                max_length=5,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.RegexValidator(
                        message="PSC musí obsahovat 5 číslic.", regex="^\\d{5}$"
                    ),
                ],
                verbose_name="PSC: ",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="slug: "),
        ),
        migrations.AlterField(
            model_name="userpicture",
            name="image1",
            field=models.ImageField(
                null=True, upload_to="employee_img/", verbose_name="img 1:"
            ),
        ),
        migrations.AlterField(
            model_name="userpicture",
            name="image2",
            field=models.ImageField(
                null=True, upload_to="employee_img/", verbose_name="img 2:"
            ),
        ),
        migrations.AlterField(
            model_name="userpicture",
            name="image3",
            field=models.ImageField(
                null=True, upload_to="employee_img/", verbose_name="img 3:"
            ),
        ),
    ]
