# Generated by Django 5.1.6 on 2025-03-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0009_alter_employeestatus_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeestatus",
            name="name",
            field=models.CharField(
                choices=[
                    ("working", "V práci"),
                    ("sick_leave", "Nemocenská"),
                    ("business_trip", "Služební cesta"),
                    ("vacation", "Dovolená"),
                    ("free", "Volno"),
                ],
                default="free",
                max_length=50,
                unique=True,
                verbose_name="Stav",
            ),
        ),
    ]
