# Generated by Django 5.1.6 on 2025-03-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0010_alter_employeestatus_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                default="nezarazeno",
                max_length=50,
                unique=True,
                verbose_name="Název oddělení",
            ),
        ),
    ]
