# Generated by Django 5.1.6 on 2025-02-20 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0010_alter_userpicture_image1_alter_userpicture_image2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="pin_code",
            field=models.CharField(
                default="0000",
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_pin",
                        message="PIN kód musí obsahovat přesně 4 číslice.",
                        regex="^\\d{4}$",
                    )
                ],
                verbose_name="PIN kód: ",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="FaceVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "face_vector",
                    models.JSONField(unique=True, verbose_name="Face vector: "),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector",
                        to="app_main.employee",
                        verbose_name="Zamestnanec: ",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserPicture",
        ),
    ]
