# Generated by Django 5.1.6 on 2025-03-20 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0011_alter_department_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="app_main.employee",
                    ),
                ),
                (
                    "new_status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_statuses",
                        to="app_main.employeestatus",
                        verbose_name="novy status",
                    ),
                ),
                (
                    "previous_status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_statuses",
                        to="app_main.employeestatus",
                        verbose_name="predesly status",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
