# Generated by Django 5.1.6 on 2025-02-20 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0011_employee_pin_code_facevector_delete_userpicture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="pin_code",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_pin",
                        message="PIN kód musí obsahovat přesně 4 číslice.",
                        regex="^\\d{4}$",
                    )
                ],
                verbose_name="PIN kód: ",
            ),
        ),
    ]
