# Generated by Django 5.1.6 on 2025-02-21 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0012_alter_employee_pin_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="pin_code_hash",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Pin Hash:"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="pin_code",
            field=models.CharField(
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_pin",
                        message="PIN kód musí obsahovat přesně 4 číslice.",
                        regex="^\\d{4}$",
                    )
                ],
                verbose_name="PIN kod: ",
            ),
        ),
    ]
