# Generated by Django 5.1.6 on 2025-03-23 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0012_employeestatushistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.RegexValidator(
                        message="Telefon musí být ve správném formátu.",
                        regex="^\\+?[0-9\\s\\-()]{5,13}$",
                    ),
                ],
                verbose_name="Telefon:",
            ),
        ),
    ]
