# Generated by Django 5.1.6 on 2025-02-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0014_alter_employee_pin_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="facevector",
            name="face_vector_fernet",
            field=models.JSONField(default=123, verbose_name="vector fernet: "),
            preserve_default=False,
        ),
    ]
