# Generated by Django 5.1.6 on 2025-02-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0015_facevector_face_vector_fernet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facevector",
            name="face_vector_fernet",
            field=models.JSONField(blank=True, verbose_name="vector fernet: "),
        ),
    ]
