# Generated by Django 5.1.6 on 2025-02-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0016_alter_facevector_face_vector_fernet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facevector",
            name="face_vector_fernet",
            field=models.TextField(blank=True, verbose_name="vector fernet:"),
        ),
    ]
