# Generated by Django 5.1.6 on 2025-03-26 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0016_alter_employee_pin_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["id"]},
        ),
    ]
