# Generated by Django 5.1.6 on 2025-02-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0017_alter_facevector_face_vector_fernet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facevector",
            name="face_vector",
            field=models.JSONField(verbose_name="Face vector: "),
        ),
    ]
