# Generated by Django 5.1.6 on 2025-03-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0018_alter_facevector_face_vector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facevector",
            name="face_vector_fernet",
        ),
    ]
